import { useState } from 'react';


import Head from 'next/head'
import Header from '../components/header'
import Section01 from '../components/section01'
import Section02 from '../components/section02'
import Section03 from '../components/section03'
import Section04 from '../components/section04'
import Section05 from '../components/section05'
import Footer from '../components/footer/footer'
import BackToTop from '../components/backToTop/backToTop';




export default function Home() {
  return (
      <div>
        <Head>
          <title>ThinkIA</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo-01.jpg" />
        </Head>
        <Header />
        <Section01 />
        <Section02 />
        <Section03 />
        <Section04 />
        <Section05 />
        <BackToTop />
        <Footer />

      </div>
  )

}
