import Head from 'next/head'
import Header from '../components/header'
import Section01 from '../components/section01'
import Section02 from '../components/section02'
import Section03 from '../components/section03'
import Section04 from '../components/section04'
import Section05 from '../components/section05'
import Footer from '../components/footer'
import BackToTop from '../components/backToTop/backToTop'
import { useEffect, useState } from 'react'

export default function Home() {

  // const [visibleSection01, setVisibleSection01] = useState(false);

  // useEffect(() => {
  //   function handleScroll() {
  //     if (document.documentElement.scrollTop > 720) {
  //       setVisibleSection01(true);
  //     }
  //   }

  //   handleScroll();

  // });

  return (
    <div>
      <Head>
        <title>ThinkIA - Soluções em Tecnologia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-03.png" />
      </Head>
      <Header />
      <Section01 />
      <Section02 />
      <Section03 />
      <Section04 />
      <Section05 />
      <BackToTop />
      <Footer />
    </div>
  )
}
